version: '3'

networks:
  nifi-local-network:
    ipam:
      config:
        - subnet: 172.35.0.0/24

services:
  nifi:
    image: local-nifi
    hostname: nifi
    container_name: nifi
    restart: unless-stopped
    networks: 
      nifi-local-network:
        ipv4_address: 172.35.0.10
    ports:
      # HTTPS
      - 8443:8443/tcp
    volumes:
      - ./database_repository:/opt/nifi/nifi-current/database_repository
      - ./flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./content_repository:/opt/nifi/nifi-current/content_repository
      - ./provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./state:/opt/nifi/nifi-current/state
      - ./logs:/opt/nifi/nifi-current/logs
      - nifi-certs:/opt/nifi/toolkit
    environment:
      NIFI_WEB_HTTPS_HOST: '0.0.0.0'
      NIFI_WEB_HTTPS_PORT: 8443

  nifi-registry:
    image: local-nifi-registry
    hostname: nifi-registry
    container_name: nifi-registry
    restart: unless-stopped
    networks: 
      nifi-local-network:
        ipv4_address: 172.35.0.11
    ports:
      # HTTPS
      - 18443:18443/tcp
    environment:
      NIFI_REGISTRY_WEB_HTTPS_HOST: '0.0.0.0'
      NIFI_REGISTRY_WEB_HTTPS_PORT: 18443

volumes:
    nifi-certs:
      external: true
