FROM apache/nifi:1.16.3

USER nifi

ARG NIFI_TOOLKIT_VERSION=1.16.3

# Create certificate for admin user
RUN cd /opt/nifi/nifi-current && \
    wget https://downloads.apache.org/nifi/${NIFI_TOOLKIT_VERSION}/nifi-toolkit-${NIFI_TOOLKIT_VERSION}-bin.zip && \
    unzip nifi-toolkit-${NIFI_TOOLKIT_VERSION}-bin.zip && \
    mv nifi-toolkit-${NIFI_TOOLKIT_VERSION} nifi-toolkit && \
    cd nifi-toolkit && \
    ./bin/tls-toolkit.sh standalone -n "localhost" --subjectAlternativeNames "nifi, nifi-registry" -C "CN=admin, OU=NIFI" -o "auth-certs-san"


USER root
RUN mkdir /opt/certs/ && \
    cp /opt/nifi/nifi-current/nifi-toolkit/auth-certs-san/localhost/keystore.jks /opt/certs/keystore.jks && \
    cp /opt/nifi/nifi-current/nifi-toolkit/auth-certs-san/localhost/truststore.jks /opt/certs/truststore.jks

USER nifi
# Set nifi.properties
ENV INITIAL_ADMIN_IDENTITY 'CN=admin, OU=NIFI'
ENV NIFI_WEB_HTTPS_HOST '0.0.0.0'
ENV NIFI_WEB_HTTPS_PORT 8443

ENV AUTH tls
ENV KEYSTORE_TYPE JKS
ENV TRUSTSTORE_TYPE JKS
ENV KEYSTORE_PATH /opt/certs/keystore.jks
ENV TRUSTSTORE_PATH /opt/certs/truststore.jks

# We have to modify environment variables, parsing values from generated by nifi-toolkit nifi.properties files
RUN KEYSTORE_PASSWORD=$(cat /opt/nifi/nifi-current/nifi-toolkit/auth-certs-san/localhost/nifi.properties | grep "nifi.security.keystorePasswd" | awk -F\= '{gsub(/"/,"",$2);print $2}') && sed -i "3i export KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" "../scripts/start.sh"

RUN cat "../scripts/start.sh"

ENTRYPOINT ["../scripts/start.sh"]
